### ISSUE TITLE
static build of html-publisher to be used in CI against A11Y tests

### ISSUE THREAD

**Issue by mahdikhashan** [boudicca-events/boudicca.events#362]
TODO

**Comment by kadhonn** [comment]
we want to run the A11Y (and most likely other e2e tests) on the current code-base, so we need to start a locally built event-html-publisher
there is quite some support for running built spring-boot applications from the spring-boot gradle plugin, so that should not be that hard.

the other thing we should/have to do is mock the dependencies of the publisher. currently the only dependency is the search-service which is called here: https://github.com/boudicca-events/boudicca.events/blob/24614a8ed309795da0858af85a0ccfdaf7765cb1/boudicca.base/publisher-event-html/src/main/kotlin/base/boudicca/publisher/event/html/service/EventService.kt#L45

so we have to mock this dependency, for that we should introduce a new interface/abstraction which has 2 implementations:
1. the "real" one which uses the SearchClient to actually call an search service
2. a mock/test implementation which always serves static data, maybe modifieable via the test?
